### ISSUE TITLE
Separator adds what's configured in attribute but also adds default separator

### ISSUE THREAD

**Issue by JoseW3b** [udayvunnam/xng-breadcrumb#15]
Hi,
when I configure separator attribute with the '>' symbol it renders ok but also adds default separator '/'. At the end we have a breadcrumb seems like 'somelabel > / anotherlabel'

I've got installed latest 3.6.0 version.

Thanks in advance.

**Comment by udayvunnam** [comment]
Hey @JoseW3b, how did you configure your separator? 

The correct way is to provide it as an input.
`<xng-breadcrumb separator=">"></xng-breadcrumb>`

**If you are having the issue even then, please provide me an online example.**
As I have tested, please see below the custom separator working fine
<img width="1680" alt="Screenshot 2019-10-12 at 7 57 46 AM" src="https://user-images.githubusercontent.com/20707504/66693444-76a95780-ecc6-11e9-80e5-a2032705ec59.png">

**Comment by JoseW3b** [comment]
Hi @udayvunnam,
after make a simple example and test like it works fine, I've noticed that the problem is bootstrap 4 styles. It put a :before content attribute in his breadcrumb component.
```css
.breadcrumb-item {
  // The separator between breadcrumbs (by default, a forward-slash: "/")
  + .breadcrumb-item {
    padding-left: $breadcrumb-item-padding;

    &::before {
      display: inline-block; // Suppress underlining of the separator in modern browsers
      padding-right: $breadcrumb-item-padding;
      color: $breadcrumb-divider-color;
      ==>content: $breadcrumb-divider;<==
    }
  }
```

If you haven't any comments, could you close the issue?

Thanks for your help.
