### ISSUE TITLE
Add support for Angular v18

### ISSUE THREAD

**Issue by lukasmatta** [udayvunnam/xng-breadcrumb#198]

**Comment by ceebows** [comment]
@udayvunnam

**Comment by apappas1129** [comment]
Installed `"xng-breadcrumb": "^11.0.0",` into a fresh Angular 18 project.
Everything seems working except that the xng-breadcrumb class names can't be selected on CSS even with  `::ng-deep` and with or increased specificity (i.e. adding class into `<xng-breadcrumb>`).

Example template:
(app.component.html)
```html
<div class="max-screen-width mx-auto py-f-m">
  <xng-breadcrumb class="ex-xng-breadcrumb" [separator]="iconTemplate">
    <ng-container *xngBreadcrumbItem="let breadcrumb; let first = first">
      <ng-container>
        @if (first) {
          <span class="iconify material-symbols--home size-m text-ex-neutral-300"></span>
          <span class="sr-only">{{ breadcrumb }}</span>
        } @else {
          {{ breadcrumb }}
        }
      </ng-container>
    </ng-container>
  </xng-breadcrumb>

  <ng-template #iconTemplate>
    <span class="iconify material-symbols--chevron-right size-m text-ex-neutral-300" aria-hidden="true"></span>
  </ng-template>
</div>
```
(app.component.css)

```css
/* BUG: xng-class selectors below do not work with or without ::ng-deep.
See  https://udayvunnam.github.io/xng-breadcrumb/#/custom-styles
For now, overriding styles directly on index.html */
::ng-deep {
  /** Even increased specificity here is not working */
  .ex-xng-breadcrumb {
    .xng-breadcrumb-separator:first-child {
      display: none;
    }

    .xng-breadcrumb-separator {
      margin: 0;
      background-color: red;
    }
  }
}
```

Nothing is selected successfully.

I don't know if there must be something done to make it work on Angular 18 so I'm reporting it here.
