### ISSUE TITLE
Add case (capitalize, uppercase, lowercase) option to breadcrumb object

### ISSUE THREAD

**Issue by KBeDevel** [udayvunnam/xng-breadcrumb#32]
I'm using `xng-breadcrumb@5.0.1` in a project with `angular-cli@9.1.3`. I'd like to be able to set a label with a full uppercase string using a breadcrumb object property

Actually, I get this using CSS in my component:

```css
::ng-deep .xng-breadcrumb-trail {
	text-transform: uppercase;
}
```
But this modify the whole project breacrumb trails to uppercase.

I'm thinking in an optional property named `case` assignable to the breadcrumb object:

```typescript
...,
data: {
  breadcrumb: {
    label: 'foo',
    case: 'capitalize | 'lowercase' | 'uppercase'
  }
}
```
